### ISSUE TITLE
Dependency Injection in Practice - Reusability of code using World

### ISSUE THREAD

**Issue by Deco354** [vermont42/racecondition.software#5]
Hi Vermont.
Firstly thanks for writing up your [article on dependency injection](http://www.racecondition.software/blog/dependency-injection/). It was a very thorough post covering a complex topic which I enjoyed reading.

 I'm very intrigued by the World solution for dependency injection. Having a singleton which is immutable in production but mutable for testing purposes is a very interesting idea.

How do you make your code reusable when using World? Would the references to `Current.date` not render every class that accesses `Current` only usable in projects that also have a World implementation with the same property?

**Comment by vermont42** [comment]
Thanks for the feedback.

Yes, any app that uses The World would need a `World` implementation. `date` is a good example of the sort of thing that should go in `World`. If you just use `Date()`, the value depends on the clock at the time of initialization. If `date` is a `World` property, you can completely control the value. The [post](https://www.pointfree.co/blog/posts/21-how-to-control-the-world) by @stephencelis provides an excellent description of the current-date-and-time use case.

I have only used The World in one app, but I envision that some dependeffects, for example `session` and `date`, would be applicable across apps. Some dependeffects, because they are are app-specific, for example `quiz` in Conjugar, would not be.

**Comment by Deco354** [comment]
Sounds good.

My only apprehension here is that any code I write that utilizes World will not be compatible with 99% of other projects should I want to drop a useful class I've written with dependeffects in to them.

I think I'll give this a go all the same. :)

**Comment by vermont42** [comment]
No, unlike, say, RxSwift, The World is pretty light-weight in terms of effects on the codebase. For example, to move code from an app using The World to an app using Swinject, you would just change instances of `Current.dependeffect` to `GlobalContainer.dependeffect`. To move code from an app using The World to an app using constructor injection, you would simply remove all instances of `Current.`, pass dependeffects to initializers, and make properties for dependeffects in all objects that use them.

I see that you are in Madrid. I hope to see you at iOSDevUK in September, where I will present a talk based on this blog post.

**Comment by Deco354** [comment]
Unfortunately not I spent my conference budget on swiftisland this year although that was my 2nd choice. Good luck though, if your speech is anything like your blog post on the subject I'm sure it will go down very well.

**Comment by vermont42** [comment]
😀
